#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.bak
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.bak
echo "8.8.8.8 facebook.com" >> ~/hosts.bak
cp -f ~/hosts.bak /etc/hosts
